config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :skip => [:registrations] 
  resources :questions
  get '/dashboard' => 'questions#dashboard'

  

  get '/login' => 'home#index', :as => :login
  root 'main#index'
  get '/users/sign_out/' =>'sessions#destroy', :as => :logout

end

app/models/question.rb
class Question < ActiveRecord::Base
   
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.admin == true
      redirect_to '/admin'
    end
    # initialize_search
    # handle_search_name
    
    session[:search_name] ||= params[:search_name]
    if session[:search_name]
      @questions = Question.where(user_id: current_user.provider_id)
      # @questions = Question.where("name LIKE ?", "%#{session[:search_name]}%")
      @questions = @questions.where("lower(name) LIKE ?", "%#{session[:search_name]}%".downcase)
      session[:search_name] = nil    
            # @teams = @teams.where(code: @players.pluck(:team))
    else
      @questions = Question.where(user_id: current_user.provider_id)
    end
    # @questions = Question.where(user_id: current_user.provider_id)
   
  end
    
  def initialize_search
    @questions = Question.where(user_id: current_user.provider_id)     #alphabetical
    session[:search_name] ||= params[:search_name]
      # session[:filter] = params[:filter]
      # params[:filter_option] = nil if params[:filter_option] == ""
      # session[:filter_option] = params[:filter_option]
  end
  
  def handle_search_name
    if session[:search_name]
      @questions = Question.where("name LIKE ?", "%#{session[:search_name].titleize}%")
          
            # @teams = @teams.where(code: @players.pluck(:team))
    else
      @questions = Question.where(user_id: current_user.provider_id)
    end
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  def login
    if current_user
      redirect_to questions_path
    end
  end
 
  def dashboard
    # Load JSON file with counselling points
    counsellingPointsFile = File.read('config/counsel_points.json')
    @counsel_points = JSON.parse(counsellingPointsFile)
    
    # Get the row id from URL
    @patient = Question.find(params[:format].to_i)
    
    # Readiness stage
    if @patient.question6 == 1
      @User_stage = 1
      @stage = "stage1"
    elsif @patient.question6 == 2 or @patient.question6 == 3
      @User_stage = 2
      @stage = "stage2"
    elsif @patient.question6 == 4 or @patient.question6 == 5
      @User_stage = 3
      @stage = "stage3"
    elsif @patient.question6 == 6
      @User_stage = 4
      @stage = "stage4"
    end
    
    # Age polarity
    @User_age = @patient.age >= 70 ? "+" : "-"
    # Risk of fracturing polarity
    @User_risk = (@patient.question2 == 4 or @patient.question2 == 5) ? "+" : "-"
    # Inadequate Literacy Polarity
    @User_literacy = (@patient.question3 == 4 or @patient.question3 == 5) ? "-" : "+"
    # Receipt of medication information polarity
    @User_priorinfo = @patient.question4 == true ? "+" : "-"
    # Trust for Medication polarity
    trust_score = (@patient.question51 + @patient.question52 + \
                    @patient.question53 + @patient.question54 + \
                    @patient.question55 + @patient.question56) / 6
    # opinion_score = opinion_total / 6
    @User_trust = trust_score > 3.17 ? "-" : "+"
  end
  
  # GET /questions
  # GET /questions.json
 
  def index
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @current_user = current_user
  end
  
  def showtouser
  end

  # GET /questions/new
  def new
    questionFile = File.read('config/questions.json')
    @questionsHash = JSON.parse(questionFile)
    @question = Question.new
    @userList = User.all
    
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Survey was successfully recorded.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name,:user_id,:mrn, :age, :question2, :question3, :question4, :question51, :question52, :question53, :question54, :question55, :question56, :question6)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.haml
.container
  %p.alert.alert-warning= flash[:notice]
  // %p#notice= notice
  %br/
  %h2.float-left{style: 'color: #79589f;'}List of Patients 
  - if current_user
    = link_to 'Logout', destroy_user_session_path, method: :delete , :class => "sticky-top float-right btn btn-outline-danger",:id => "right"
    %br/
  %br/
  
  %form.form-inline{:action => "", :method => "GET"}
    %input.form-control.mr-sm-2{:name => "search_name","aria-label" => "Search", :placeholder => "Search", :type => "search"}/ 
    // %input{:type => "submit", :value => "Search for Patient"}/
    %input.btn.btn-outline-success.my-2.my-sm-0{:type => "submit", :value => "Search"}/
    // = link_to 'All Patients', root_path , :class => "float-right"
  = link_to 'All Patients', root_path , :class => "float-right"  
  %br/


  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th MRN
        %th Age
      
        %th{:colspan => "3"} Actions
    %tbody
      - @questions.each do |question|
        %tr
          %td= link_to question.name,dashboard_path(question)
          %td= question.mrn
          %td= question.age
          %td= link_to 'Show Response', question#showtouser
          // %td= link_to 'Edit Response', edit_question_path(question)
          // %td= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  // = link_to 'New Response', new_question_path

  // - if current_user
  //   = link_to 'Logout', destroy_user_session_path, method: :delete , :class => "btn btn-outline-success",:id => "center"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MedicalPersistanceSystem
    // = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    // = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/main/index.html.haml
.container-fluid.bg-image
  .row.no-gutter
    .d-none.d-md-flex.col-md-4.col-lg-6
      .login.d-flex.align-items-center.py-5
        .container
          %h3.text-center.login-heading.mb-4 How aware are you about Osteoporosis ? 
          %h3.text-center.login-heading.mb-4 Osteoporosis affects 200 million people worldwide. Women are more prone to osteoporosis. 1 out of 5 women receive an evaluation for osteoporosis. From this 1 out of 2 women are prescribed medication. 
          %h3.text-center.login-heading.mb-4 Take our Survey. Then your provider will receive this information and will help better guide you.
          = link_to 'Take New Survey', new_question_path, :class => "float-center btn btn-primary btn-lg",:id => "center"
            
    .d-none.d-md-flex.col-md-4.col-lg-6
      .login.d-flex.align-items-center.py-5
        .container
          = link_to 'Admin/Provider Login', '/login', :class => "btn btn-primary btn-lg",:id => "center"

app/views/questions/_form.html.haml
= form_for(@question) do |f|
  - if @question.errors.any?
    #error_explanation
      %h2
        = pluralize(@question.errors.count, "error")
        prohibited this question from being saved:
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message
  .row
    .col
      .form-group
        = f.label :name,'Please enter your full name:',:class => "font-weight-bold"
        %br/
        = f.text_field :name,:class => "form-control",:required => true

    .col
      .form-group
        = f.label :user_id,'Primary Provider',:class => "font-weight-bold"
        %br/
        //= f.text_field :user_id, :class => "form-control",:required => true
   
        = f.select(:user_id) do 
          - @userList.each do |l|
            = content_tag(:option, l.provider_id, value: l.provider_id, :class => "form form-group form-control",:required => true )

  %br/ 
  .row
    .col
      
      .form-group
        = f.label :mrn,'Please enter your Medical Record Number',:class => "font-weight-bold"
        %br/
        = f.text_field :mrn, :class => "form-control",:required => true, :maxlength => "10"
    .col
      .form-group
      
        = f.label :age, 'Please enter your age (in years):',:class => "font-weight-bold"
        %br/
        = f.number_field :age,:class => "form-control",:required => true, :min => 0 , :max => 199        
  %br/
  // .form-group
  //   = f.label :age, 'Please enter your age (in years):'
  //   %br/
  //   = f.number_field :age,:class => "form-control",:required => true
  %br/
  .form-group
    = f.label :question2,'Compared to women your age, how would you rate your own risk of fracturing or breaking a bone?',:class => "font-weight-bold"
  .radio 
    %label
      = f.radio_button :question2, 1, :required => true
      Much Lower     
  .radio
    %label
      = f.radio_button :question2, 2
      A Little Lower
  .radio
    %label
      = f.radio_button :question2, 3
      About the same 
  .radio
    %label
      = f.radio_button :question2, 4
      A Little Higher
  .radio
    %label
      = f.radio_button :question2, 5
      Much Higher
  %br/
  .form-group
    = f.label :question3,'How confident are you filling out medical forms by yourself?',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question3, 1,:required => true
      Not at all
  .radio
    %label
      = f.radio_button :question3, 2
      A Little Bit
  .radio
    %label
      = f.radio_button :question3, 3
      Somewhat
  .radio
    %label
      = f.radio_button :question3, 4
      Quite a Bit
  .radio
    %label
      = f.radio_button :question3, 5
      Extremely
  %br/
  .form-group
    = f.label :question4,'People get information about osteoporosis medication from different sources. Have you recieved information about possible osteoporosis medication in past year?',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question4, true,:required => true
      Yes
  .radio
    %label
      = f.radio_button :question4, false
      No
  %br/ 
  .form-group
    = f.label :question51,'There are better ways for me to treat my osteoporosis besides medication.',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question51, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question51, 2
      Disagree
  .radio
    %label
      = f.radio_button :question51, 3
      Neutral
  .radio
    %label
      = f.radio_button :question51, 4
      Agree
  .radio
    %label
      = f.radio_button :question51, 5
      Strongly Agree
  %br/
  .form-group
    = f.label :question52, 'Doctors are too quick to prescribe medication.',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question52, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question52, 2
      Disagree
  .radio
    %label
      = f.radio_button :question52, 3
      Neutral
  .radio
    %label
      = f.radio_button :question52, 4
      Agree
  .radio
    %label
      = f.radio_button :question52, 5
      Strongly Agree
  %br/
  .form-group
    = f.label :question53, 'Doctors often give medication when advice would be better',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question53, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question53, 2
      Disagree
  .radio
    %label
      = f.radio_button :question53, 3
      Neutral
  .radio
    %label
      = f.radio_button :question53, 4
      Agree
  .radio
    %label
      = f.radio_button :question53, 5
      Strongly Agree
  %br/
  .form-group
    = f.label :question54, 'I can take care of my osteoporosis without medication.',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question54, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question54, 2
      Disagree
  .radio
    %label
      = f.radio_button :question54, 3
      Neutral
  .radio
    %label
      = f.radio_button :question54, 4
      Agree
  .radio
    %label
      = f.radio_button :question54, 5
      Strongly Agree
  %br/
  .form-group
    = f.label :question55, 'Medications often cause more problems than they solve.',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question55, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question55, 2
      Disagree
  .radio
    %label
      = f.radio_button :question55, 3
      Neutral
  .radio
    %label
      = f.radio_button :question55, 4
      Agree
  .radio
    %label
      = f.radio_button :question55, 5
      Strongly Agree
  %br/
  .form-group
    = f.label :question56, 'I prefer not to take medication',:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question56, 1,:required => true
      Strongly Disgree
  .radio
    %label
      = f.radio_button :question56, 2
      Disagree
  .radio
    %label
      = f.radio_button :question56, 3
      Neutral
  .radio
    %label
      = f.radio_button :question56, 4
      Agree
  .radio
    %label
      = f.radio_button :question56, 5
      Strongly Agree
  %br/
    
  .form-group
    = f.label :question6, "Please choose the one statement that best reflects your feelings about recieving medicines now",:class => "font-weight-bold"
  .radio
    %label
      = f.radio_button :question6, 1,:required => true
      I do not think I need treatment for osteoporosis    
  .radio
    %label
      = f.radio_button :question6, 2
      I am aware that there are treatments available for my osteoporosis, but I have never thought seriously about using these medications.
  .radio
    %label
      = f.radio_button :question6, 3
      I have considered of using or have prevously used osteoporosis medication, but I have decided against taking it     
  .radio
    %label
      = f.radio_button :question6, 4
      I am currently considering the use of osteoporosis medication, but I have not made up my mind. 
  .radio
    %label
      = f.radio_button :question6, 5
      I have decided to use osteoporosis medication, but I have not yet started taking anything  
  .radio
    %label
      = f.radio_button :question6, 6
      I have started taking medication for osteoporosis    
  
    %br/  
    %br/
    
  .form-group#center
    
    
    // = link_to 'Go Back', root_path, :class => "btn btn-danger"
    
    = f.submit  'Submit Response', :class => "btn btn-success"

app/views/questions/edit.html.haml
.container
    %br/
    %h1.text-center Edit Response
    %br/
    = render 'form'
    = link_to 'Show', @question
    |
    = link_to 'Back', root_path
    %br/
    %br/
    

app/views/questions/index.html.haml
.container-fluid.bg-image
  .row.no-gutter
    .d-none.d-md-flex.col-md-4.col-lg-6
      .login.d-flex.align-items-center.py-5
        .container
          = link_to 'Take New Survey', new_question_path, :class => "btn btn-primary btn-lg",:id => "center"

app/views/questions/login.html.haml
.container-fluid.bg-image
  .row.no-gutter
    .d-none.d-md-flex.col-md-4.col-lg-6
      .login.d-flex.align-items-center.py-5
        .container
          = link_to 'Take New Survey', new_question_path, :class => "btn btn-primary btn-lg",:id => "center"
     
    .col-md-8.col-lg-6
      .login.d-flex.align-items-center.py-5
        .container
          .row
            .col-md-9.col-lg-8.mx-auto
              %h3.login-heading.mb-4 Welcome Sign In!
              %form{:action => "/questions", :method => "GET"}
                .form-label-group
                  %input#inputEmail.form-control{:autofocus => "", :placeholder => "Email address", :required => "", :type => "email"}/
                  %label{:for => "inputEmail"} Email address
                .form-label-group
                  %input#inputPassword.form-control{:placeholder => "Password", :required => "", :type => "password"}/
                  %label{:for => "inputPassword"} Password
                .custom-control.custom-checkbox.mb-3
                  %input#customCheck1.custom-control-input{:type => "checkbox"}/
                  %label.custom-control-label{:for => "customCheck1"} Remember password
                %button.btn.btn-lg.btn-primary.btn-block.btn-login.text-uppercase.font-weight-bold.mb-2{:type => "submit"} Sign in
                .text-center
                  %a.small{:href => "#"} Forgot password?

app/views/questions/new.html.haml
%link{:rel => "stylesheet", :type => "text/css", :href => "/form"}
.body{style: 'background: #ffffff;' }
    %br
    %h1.text-center{style: 'color: #007bff;'} New Survey
    %br
    .container{style: 'background: #ffffff;'}
        = render 'form'
        = link_to 'Back', root_path
        %br
        %br
        %br

app/views/questions/show.html.haml
.container
  %p#notice= notice
  %h2.text-center{style: 'color: #79589f;'} Response
  %br/
  %p
    %strong Doctor's Name:
    = @question.user_id
  %p
    %strong Name:
    = @question.name
  %p
    %strong MRN:
    = @question.mrn
  %p
    %strong Age:
    = @question.age
  %p
    %strong Compared to women your age, how would you rate your own risk of fraturing or breaking a bone?:
    = ("Much lower" if @question.question2==1)
    = ("A little lower" if @question.question2==2)
    = ("About the same" if @question.question2==3)
    = ("A little higher" if @question.question2==4)
    = ("Much higher" if @question.question2==5)
  %p
    %strong How confident are you filling out medical forms by yourself?:
    = ("Not at all" if @question.question3==1)
    = ("A little bit" if @question.question3==2)
    = ("Somewhat" if @question.question3==3)
    = ("Quite a bit" if @question.question3==4)
    = ("Extremely" if @question.question3==5)
  %p
    %strong People get information about osteoporosis medication from different sources. Have you recieved information about possible osteoporosis medication in past year?:
    = ("No" if @question.question4==false)
    = ("Yes" if @question.question4==true)
  %p
    %strong There are better ways for me to treat my osteoporosis besides medication:
    = ("Strongly Disagree" if @question.question51==1)
    = ("Disagree" if @question.question51==2)
    = ("Neutral" if @question.question51==3)
    = ("Agree" if @question.question51==4)
    = ("Strongly Agree" if @question.question51==5)
  %p
    %strong Doctors are too quick to prescribe medication:
    = ("Strongly Disagree" if @question.question52==1)
    = ("Disagree" if @question.question52==2)
    = ("Neutral" if @question.question52==3)
    = ("Agree" if @question.question52==4)
    = ("Strongly Agree" if @question.question52==5)
  %p
    %strong Doctors of often give medication when advice would be better:
    = ("Strongly Disagree" if @question.question53==1)
    = ("Disagree" if @question.question53==2)
    = ("Neutral" if @question.question53==3)
    = ("Agree" if @question.question53==4)
    = ("Strongly Agree" if @question.question53==5)
  %p
    %strong I can take care of my osteoporosis without medication:
    = ("Strongly Disagree" if @question.question54==1)
    = ("Disagree" if @question.question54==2)
    = ("Neutral" if @question.question54==3)
    = ("Agree" if @question.question54==4)
    = ("Strongly Agree" if @question.question54==5)
  %p
    %strong Medications often cause more problems than they solve:
    = ("Strongly Disagree" if @question.question55==1)
    = ("Disagree" if @question.question55==2)
    = ("Neutral" if @question.question55==3)
    = ("Agree" if @question.question55==4)
    = ("Strongly Agree" if @question.question55==5)
  %p
    %strong I prefer not to take medication:
    = ("Strongly Disagree" if @question.question56==1)
    = ("Disagree" if @question.question56==2)
    = ("Neutral" if @question.question56==3)
    = ("Agree" if @question.question56==4)
    = ("Strongly Agree" if @question.question56==5)
  %p
    %strong Please choose the one statement that best reflects your feelings about recieving medicines now:
    = ("I do not think I need treatment for osteoporosis" if @question.question6==1)
    = ("I am aware that there are treatments available for my osteoporosis, but I have never thought seriously about using these medications" if @question.question6==2)
    = ("I have considered using or have previously used osteoporosis medication, but I have decided against taking it" if @question.question6==3)
    = ("I am currently considering the use of osteoporosis medication, but I have not made up my mind" if @question.question6==4)
    = ("I have decided to use osteoporosis medication, but I have not yet started taking anything" if @question.question6==5)
    = ("I have started medication for osteoporosis" if @question.question6==5)
  
  %br/
  - if not user_signed_in?
    = link_to 'Edit Response', edit_question_path(@question),:class => "float-center btn btn-secondary"
    = link_to '  Submit ', root_path, :class => " btn btn-danger"
  - else
    = link_to '  Back ',  '/login', :class => " btn btn-danger"
// %span#pad
// %span#pad 
// %span#pad 

// .container
//   - if @current_user.provider_id == true
//     = link_to '  Done ', root_path, :class => " btn btn-danger"
//   -else

// = link_to 'Edit Response', edit_question_path(@question),:class => "float-center btn btn-secondary"
// = link_to '  Done ', root_path, :class => " btn btn-danger"
%br/
%br/

app/views/questions/showtouser.html.haml
.container
  %p#notice= notice
  %h2.text-center Patient Response
  %br/
  %p
    %strong Name:
    = @question.user_id
  %p
    %strong Name:
    = @question.name
  %p
    %strong MRN:
    = @question.mrn
  %p
    %strong Age:
    = @question.age
  %p
    %strong Compared to women your age, how would you rate your own risk of fraturing or breaking a bone?:
    = ("Much lower" if @question.question2==1)
    = ("A little lower" if @question.question2==2)
    = ("About the same" if @question.question2==3)
    = ("A little higher" if @question.question2==4)
    = ("Much higher" if @question.question2==5)
  %p
    %strong How confident are you filling out medical forms by yourself?:
    = ("Not at all" if @question.question3==1)
    = ("A little bit" if @question.question3==2)
    = ("Somewhat" if @question.question3==3)
    = ("Quite a bit" if @question.question3==4)
    = ("Extremely" if @question.question3==5)
  %p
    %strong People get information about osteoporosis medication from different sources. Have you recieved information about possible osteoporosis medication in past year?:
    = ("No" if @question.question4==false)
    = ("Yes" if @question.question4==true)
  %p
    %strong There are better ways for me to treat my osteoporosis besides medication:
    = ("Strongly Disagree" if @question.question51==1)
    = ("Disagree" if @question.question51==2)
    = ("Neutral" if @question.question51==3)
    = ("Agree" if @question.question51==4)
    = ("Strongly Agree" if @question.question51==5)
  %p
    %strong Doctors are too quick to prescribe medication:
    = ("Strongly Disagree" if @question.question52==1)
    = ("Disagree" if @question.question52==2)
    = ("Neutral" if @question.question52==3)
    = ("Agree" if @question.question52==4)
    = ("Strongly Agree" if @question.question52==5)
  %p
    %strong Doctors of often give medication when advice would be better:
    = ("Strongly Disagree" if @question.question53==1)
    = ("Disagree" if @question.question53==2)
    = ("Neutral" if @question.question53==3)
    = ("Agree" if @question.question53==4)
    = ("Strongly Agree" if @question.question53==5)
  %p
    %strong I can take care of my osteoporosis without medication:
    = ("Strongly Disagree" if @question.question54==1)
    = ("Disagree" if @question.question54==2)
    = ("Neutral" if @question.question54==3)
    = ("Agree" if @question.question54==4)
    = ("Strongly Agree" if @question.question54==5)
  %p
    %strong Medications often cause more problems than they solve:
    = ("Strongly Disagree" if @question.question55==1)
    = ("Disagree" if @question.question55==2)
    = ("Neutral" if @question.question55==3)
    = ("Agree" if @question.question55==4)
    = ("Strongly Agree" if @question.question55==5)
  %p
    %strong I prefer not to take medication:
    = ("Strongly Disagree" if @question.question56==1)
    = ("Disagree" if @question.question56==2)
    = ("Neutral" if @question.question56==3)
    = ("Agree" if @question.question56==4)
    = ("Strongly Agree" if @question.question56==5)
  %p
    %strong Please choose the one statement that best reflects your feelings about recieving medicines now:
    = ("I do not think I need treatment for osteoporosis" if @question.question6==1)
    = ("I am aware that there are treatments available for my osteoporosis, but I have never thought seriously about using these medications" if @question.question6==2)
    = ("I have considered using or have previously used osteoporosis medication, but I have decided against taking it" if @question.question6==3)
    = ("I am currently considering the use of osteoporosis medication, but I have not made up my mind" if @question.question6==4)
    = ("I have decided to use osteoporosis medication, but I have not yet started taking anything" if @question.question6==5)
    = ("I have started medication for osteoporosis" if @question.question6==5)
  
  %br/
// %span#pad
// %span#pad 
// %span#pad 

.container
//   = link_to 'Edit Response', edit_question_path(@question),:class => "btn btn-secondary"
  = link_to '  Back ', root_path, :class => " btn btn-danger"

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/